### ISSUE TITLE
Обзёрвер

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/To-Do-List#3]
https://github.com/AnnLuschik/To-Do-List/blob/41d13bed0672596110ac0dd8210731f81fd30683/script.js#L63

Будет неплохо, если ты пояснишь зачем тебе здесь обзёрвер понадобился и разобралась ли ты вообще с тем, что такое наблюдатель и как оно работает)

**Comment by AnnLuschik** [comment]
Этот обзёрвер нужен для того, чтобы перезаписывать значение в заголовке блока (количество задач) при каждом изменении в DOM, которое связано с элементами списка. Он наблюдает за контейнером, в котором находятся все три блока, за изменениями, связанными со всеми элементами-потомками (детьми и детьми детей). Думаю, что разобралась.
Явно тут есть какое-то более простое решение, но мне оно в голову, значит, не пришло.

**Comment by casa7x** [comment]
Напиши функцию, которая будет возвращать актуальное количество элементов в списке и при каждом изменениии списка, ты будешь её вызывать. И не надо тебе никаких обзёрверов здесь)

**Comment by AnnLuschik** [comment]
Готово.
