### ISSUE TITLE
Лишние значения

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/To-Do-List#4]
https://github.com/AnnLuschik/To-Do-List/blob/41d13bed0672596110ac0dd8210731f81fd30683/script.js#L135

Тебе не обязательно передавать в резолв истину, а в реджект, ложно. Они и так по своей сути означают это, передаёшь только если надо какие-то данные дальше пробросить

**Comment by AnnLuschik** [comment]
Исправлено.
