### ISSUE TITLE
Очищение всех элементов

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/To-Do-List#9]
https://github.com/AnnLuschik/To-Do-List/blob/41d13bed0672596110ac0dd8210731f81fd30683/script.js#L238

Можно просто взять innerHTML у списка к примеру и очистить его, либо взять длинну у коллекции и прировныть её к 0 и не надо превращать всё будет в массив, перебирать его и удалять каждый элемент поотдельности

**Comment by AnnLuschik** [comment]
Готово. Выполнено с помощью innerHTML.
